# Generated by Django 5.2.17 on 2026-08-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TallySyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('import', 'Import from Tally'), ('export', 'Export to Tally')], max_length=10)),
                ('entity_type', models.CharField(choices=[('ledger', 'Ledger'), ('voucher', 'Voucher'), ('stock_item', 'Stock Item'), ('contact', 'Contact'), ('invoice', 'Invoice')], max_length=20)),
                ('entity_id', models.CharField(blank=True, default='', help_text='ID of the synced entity', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('request_xml', models.TextField(blank=True, default='')),
                ('response_xml', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('tally_ledger_name', models.CharField(blank=True, default='', max_length=200)),
                ('tally_voucher_no', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tally Sync Log',
                'verbose_name_plural': 'Tally Sync Logs',
                'db_table': 'tally_sync_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
