# Generated by Django 5.2.17 on 2026-08-16 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'crm_product_categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('sku', models.CharField(blank=True, default='', max_length=100)),
                ('product_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service')], default='product', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(blank=True, default='pcs', help_text='e.g., pcs, hours, kg', max_length=50)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, help_text='Tax %', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'crm_products',
            },
        ),
    ]
